## Docker image: https://hub.docker.com/_/python
image: docker.io/python:3.7

stages:
  - linting
  - generate_documentation

.install_prerequesites_pip: &install_prerequesites_pip |
  pip install -r requirements.txt

.setup_for_html: &setup_for_html |
  apt-get update
  apt-get -y install pandoc

linting:
  stage: linting
  allow_failure: yes
  rules:
    - if: $CI_MERGE_REQUEST_ID             # Execute jobs in merge request context
    - if: $CI_COMMIT_BRANCH == 'master'    # Execute jobs when a new commit is pushed to master branch
  script:
    - *install_prerequesites_pip
    - yamllint kernels.yml

pages:
  stage: generate_documentation
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'    # Execute jobs when a new commit is pushed to master branch
  script:
    - *install_prerequesites_pip
    - *setup_for_html
    - ./scripts/generate_images_stats.py
    - ./scripts/generate_images_table.py
    - ./scripts/generate_kernels_stats.py
    - ./scripts/generate_kernels_table.py
    - mkdir -p ./public/
    - cp ./.gitlab/404.html   ./public/
    - cp ./.gitlab/public.css ./public/
    - pandoc -s ./.gitlab/www.md  -o ./public/index.html        -c public.css
    - pandoc -s ./image-stats.md  -o ./public/image-stats.html  -c public.css
    - pandoc -s ./images.md       -o ./public/images.html       -c public.css
    - pandoc -s ./kernel-stats.md -o ./public/kernel-stats.html -c public.css
    - pandoc -s ./kernels.md      -o ./public/kernels.html      -c public.css
  artifacts:
    paths:
      - ./public
    expire_in: 1 week
