## Docker image: https://hub.docker.com/_/python
image: docker.io/python:3.7

stages:
  - linting
  - generate_documentation

.install_prerequesites_pip: &install_prerequesites_pip |
  pip install -r requirements.txt

.setup_for_html: &setup_for_html |
  apt-get update
  apt-get -y install pandoc

linting:
  stage: linting
  allow_failure: yes
  rules:
    - if: $CI_MERGE_REQUEST_ID             # Execute jobs in merge request context
    - if: $CI_COMMIT_BRANCH == 'master'    # Execute jobs when a new commit is pushed to master branch
  script:
    - *install_prerequesites_pip
    - yamllint kernels.yml

pages:
  stage: generate_documentation
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'    # Execute jobs when a new commit is pushed to master branch
  script:
    - *install_prerequesites_pip
    - *setup_for_html
    - ./scripts/generate_images_stats.py
    - ./scripts/generate_images_table.py
    - ./scripts/generate_kernels_stats.py
    - ./scripts/generate_kernels_table.py
    - mkdir -pv ./public/
    - cp -v ./.gitlab/404.html   ./public/
    - cp -v ./.gitlab/public.css ./public/
    - pandoc --standalone ./.gitlab/www.md  --css=public.css --include-in-header=./.gitlab/header.html --output=./public/index.html
    - pandoc --standalone ./image-stats.md  --css=public.css --include-in-header=./.gitlab/header.html --output=./public/image-stats.html
    - pandoc --standalone ./images.md       --css=public.css --include-in-header=./.gitlab/header.html --output=./public/images.html
    - pandoc --standalone ./kernel-stats.md --css=public.css --include-in-header=./.gitlab/header.html --output=./public/kernel-stats.html
    - pandoc --standalone ./kernels.md      --css=public.css --include-in-header=./.gitlab/header.html --output=./public/kernels.html
    - find public/ -type f -name '*.html' -exec sed -i 's_<table>_<table id="pretty">_' {} +
  artifacts:
    paths:
      - ./public
    expire_in: 1 week
