image: "python:3.7"

stages:
  - generate_documentation
  
pages:
  stage: generate_documentation
  script:
  - python scripts/generate_documentation.py
  artifacts:
    paths:
    - public/devices.md
    expire_in: 1 week